import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import Link from "next/link";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Main from "./components/Main";
import MenuProvider from "./context/MenuContext";
import { Anek_Devanagari } from "next/font/google";

const anekDeva = Anek_Devanagari({
  subsets: ["latin"],
  display: "swap",
  fontWeight: "400",
});
//import ThemeProvider from "./context/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next Portfolio",
  description: "Generated by create next app",
  subtitle: "This is a Portfolio website using NextJs ",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${anekDeva.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MenuProvider>
          <Navbar />
          <main style={{ display: "flex" }}>
            <Main />
            {children}
          </main>
          <Footer />
        </MenuProvider>
      </body>
    </html>
  );
}
